USE [EDW_STAGE]
GO

/****** Object:  Table [dbo].[SOFTRAX9_CUSTOMER_ARCHIVE]    Script Date: 12/27/2022 9:38:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SOFTRAX9_CUSTOMER_ARCHIVE](
	[BK_Hash] [char](40) NULL,
	[loadDttm] [datetime2](7) NULL,
	[load_date] [smalldatetime] NULL,
	[sourcesystem_id] [int] NULL,
	[cus_cd] [varchar](10) NULL,
	[cus_grp_cd] [varchar](6) NULL,
	[cus_name] [varchar](40) NULL,
	[cus_addr1] [varchar](40) NULL,
	[cus_addr2] [varchar](40) NULL,
	[cus_city] [varchar](30) NULL,
	[cus_state] [varchar](30) NULL,
	[cus_zip] [varchar](15) NULL,
	[cus_country] [varchar](3) NULL,
	[cus_phone] [varchar](25) NULL,
	[cus_fax] [varchar](25) NULL,
	[cus_comment] [varchar](60) NULL,
	[cus_ship_via] [varchar](10) NULL,
	[cus_bill_to] [varchar](10) NULL,
	[cus_ship_to] [varchar](10) NULL,
	[cus_class] [varchar](10) NULL,
	[cus_ar_seg1] [varchar](9) NULL,
	[cus_ar_seg2] [varchar](9) NULL,
	[cus_ar_seg3] [varchar](9) NULL,
	[cus_ar_seg4] [varchar](9) NULL,
	[cus_ar_seg5] [varchar](9) NULL,
	[cus_ar_seg6] [varchar](9) NULL,
	[cus_ar_seg7] [varchar](9) NULL,
	[cus_ar_seg8] [varchar](9) NULL,
	[cus_ar_seg9] [varchar](9) NULL,
	[cus_ar_segty] [varchar](2) NULL,
	[cus_status] [varchar](2) NULL,
	[cus_app_st] [varchar](2) NULL,
	[cus_category] [varchar](10) NULL,
	[cus_active_dt] [datetime] NULL,
	[cus_inactive_dt] [datetime] NULL,
	[cus_sub_class] [varchar](10) NULL,
	[cus_contact] [varchar](40) NULL,
	[cus_contact2] [varchar](40) NULL,
	[cus_phone2] [varchar](25) NULL,
	[cus_fax2] [varchar](25) NULL,
	[cus_pmt_type] [varchar](2) NULL,
	[cus_term_cd] [varchar](10) NULL,
	[cus_sal_cd] [varchar](6) NULL,
	[cus_cr_limit] [money] NULL,
	[cus_txt] [char](1) NULL,
	[cus_curr_cd] [varchar](4) NULL,
	[cus_price_type] [varchar](3) NULL,
	[cus_route_st] [varchar](2) NULL,
	[cus_tax1_cd] [varchar](10) NULL,
	[cus_tax2_cd] [varchar](10) NULL,
	[cus_tax3_cd] [varchar](10) NULL,
	[cus_tax4_cd] [varchar](10) NULL,
	[cus_tax5_cd] [varchar](10) NULL,
	[cus_cycle_cd] [varchar](10) NULL,
	[cus_finc_cd] [varchar](6) NULL,
	[cus_charge_cd] [varchar](12) NULL,
	[cus_renewal_dt] [datetime] NULL,
	[cus_collect_fl] [char](1) NULL,
	[cus_credit_hold] [char](1) NULL,
	[cus_terr_cd] [varchar](5) NULL,
	[cus_county] [varchar](26) NULL,
	[cus_city_limit_cd] [char](1) NULL,
	[cus_geocode] [int] NULL,
	[cus_geocode_used] [char](1) NULL,
	[cus_addr3] [varchar](40) NULL,
	[cus_addr4] [varchar](40) NULL,
	[cus_sched_cd] [varchar](10) NULL,
	[cus_balance] [money] NULL,
	[cus_onorder] [money] NULL,
	[cus_open_cr] [money] NULL,
	[cus_ytd_billings] [money] NULL,
	[cus_ytd_shipments] [money] NULL,
	[cus_last_inv_amt] [money] NULL,
	[cus_last_pmt_amt] [money] NULL,
	[cus_last_bill_dt] [datetime] NULL,
	[cus_last_pmt_dt] [datetime] NULL,
	[sx_cus_sal_cd2] [varchar](6) NULL,
	[sx_cus_sal_cd3] [varchar](6) NULL,
	[cus_xspc_skuph_cd] [varchar](3) NULL,
	[cus_xemail1] [varchar](80) NULL,
	[cus_xemail2] [varchar](80) NULL,
	[sfa_company_skey] [int] NULL,
	[cus_xsxpb_code] [varchar](3) NULL,
	[sxdat_pk] [int] NULL,
	[cus_registration_no] [varchar](30) NULL,
	[cus_company] [varchar](6) NULL,
	[cus_inv_deliv_opt] [char](1) NULL,
	[cus_pro_deliv_opt] [char](1) NULL,
	[cus_bill_deliv_opt] [char](1) NULL,
	[cus_ext_ref] [int] NULL,
	[cus_fl_consolidated] [char](1) NULL,
	[cus_createid] [varchar](30) NULL,
	[cus_createdttm] [datetime] NULL,
	[cus_modid] [varchar](30) NULL,
	[cus_moddttm] [datetime] NULL,
	[cus_vsoe_skuph_cd] [varchar](3) NULL
) ON [SECONDARY]
GO


