USE [EDW_STAGE]
GO

/****** Object:  Table [dbo].[CRM_ACCOUNT]    Script Date: 12/27/2023 9:28:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CRM_ACCOUNT](
	[BI_load_date] [datetime2](7) NULL,
	[sourcesystem_id] [int] NULL,
	[ACCOUNTID] [nchar](12) NOT NULL,
	[TYPE] [nvarchar](64) NULL,
	[ACCOUNT] [nvarchar](255) NULL,
	[DIVISION] [nvarchar](64) NULL,
	[SICCODE] [nvarchar](64) NULL,
	[PARENTID] [nchar](12) NULL,
	[DESCRIPTION] [nvarchar](128) NULL,
	[ADDRESSID] [nchar](12) NULL,
	[SHIPPINGID] [nchar](12) NULL,
	[REGION] [nvarchar](64) NULL,
	[MAINPHONE] [nvarchar](32) NULL,
	[ALTERNATEPHONE] [nvarchar](32) NULL,
	[FAX] [nvarchar](32) NULL,
	[TOLLFREE] [nvarchar](32) NULL,
	[TOLLFREE2] [nvarchar](32) NULL,
	[OTHERPHONE1] [nvarchar](32) NULL,
	[OTHERPHONE2] [nvarchar](32) NULL,
	[OTHERPHONE3] [nvarchar](32) NULL,
	[EMAIL] [nvarchar](128) NULL,
	[EMAILTYPE] [nvarchar](64) NULL,
	[WEBADDRESS] [nvarchar](128) NULL,
	[SECCODEID] [nchar](12) NULL,
	[REVENUE] [decimal](17, 4) NULL,
	[EMPLOYEES] [int] NULL,
	[INDUSTRY] [nvarchar](64) NULL,
	[CREDITRATING] [nvarchar](64) NULL,
	[NOTES] [ntext] NULL,
	[STATUS] [nvarchar](64) NULL,
	[ACCOUNTMANAGERID] [nchar](12) NULL,
	[REGIONALMANAGERID] [nchar](12) NULL,
	[DIVISIONALMANAGERID] [nchar](12) NULL,
	[NATIONALACCOUNT] [nchar](1) NULL,
	[TARGETACCOUNT] [nchar](1) NULL,
	[TERRITORY] [nvarchar](64) NULL,
	[CREATEUSER] [nchar](12) NULL,
	[MODIFYUSER] [nchar](12) NULL,
	[CREATEDATE] [datetime] NULL,
	[MODIFYDATE] [datetime] NULL,
	[ACCOUNT_UC] [nvarchar](255) NULL,
	[AKA] [nvarchar](64) NULL,
	[CURRENCYCODE] [nvarchar](64) NULL,
	[INTERNALACCOUNTNO] [nvarchar](32) NULL,
	[EXTERNALACCOUNTNO] [nvarchar](32) NULL,
	[PARENTACCOUNTNO] [nvarchar](32) NULL,
	[ALTERNATEKEYPREFIX] [nvarchar](64) NULL,
	[ALTERNATEKEYSUFFIX] [nvarchar](64) NULL,
	[DEFAULTTICKETSECCODEID] [nchar](12) NULL,
	[NOTIFYDEFECTS] [nchar](1) NULL,
	[NOTIFYONCLOSE] [nchar](1) NULL,
	[NOTIFYONSTATUS] [nchar](1) NULL,
	[SHORTNOTES] [nvarchar](255) NULL,
	[USERFIELD1] [nvarchar](80) NULL,
	[USERFIELD2] [nvarchar](80) NULL,
	[USERFIELD3] [nvarchar](80) NULL,
	[USERFIELD4] [nvarchar](80) NULL,
	[USERFIELD5] [nvarchar](80) NULL,
	[USERFIELD6] [nvarchar](80) NULL,
	[USERFIELD7] [nvarchar](80) NULL,
	[USERFIELD8] [nvarchar](80) NULL,
	[USERFIELD9] [nvarchar](80) NULL,
	[USERFIELD10] [nvarchar](80) NULL,
	[CAMPAIGNID] [nchar](12) NULL,
	[DONOTSOLICIT] [nchar](1) NULL,
	[SCORE] [nvarchar](32) NULL,
	[TICKER] [nvarchar](16) NULL,
	[SUBTYPE] [nvarchar](64) NULL,
	[LEADSOURCEID] [nchar](12) NULL,
	[IMPORTSOURCE] [nvarchar](24) NULL,
	[ENGINEERID] [nchar](12) NULL,
	[SALESENGINEERID] [nchar](12) NULL,
	[RELATIONSHIP] [int] NULL,
	[LASTHISTORYBY] [nchar](12) NULL,
	[LASTHISTORYDATE] [datetime] NULL,
	[BUSINESSDESCRIPTION] [nvarchar](2000) NULL,
	[WEBADDRESS2] [nvarchar](128) NULL,
	[WEBADDRESS3] [nvarchar](128) NULL,
	[WEBADDRESS4] [nvarchar](128) NULL,
	[GLOBALSYNCID] [nvarchar](36) NULL,
	[APPID] [nvarchar](12) NULL,
	[TICK] [int] NULL,
	[LASTERPSYNCUPDATE] [datetime] NULL,
	[PRIMARYOPERATINGCOMPID] [nvarchar](12) NULL,
	[PROMOTEDTOACCOUNTING] [nvarchar](1) NULL,
	[CREATESOURCE] [nvarchar](64) NULL,
	[ERPEXTID] [nvarchar](100) NULL,
	[ERPCUSTTYPE] [nvarchar](64) NULL,
	[ERPCARRIERNAME] [nvarchar](64) NULL,
	[ERPINCOTERM] [nvarchar](64) NULL,
	[ERPTERRITORY] [nvarchar](64) NULL,
	[ERPPREFERENCE] [nchar](1) NULL,
	[ERPINTERNALCUST] [nvarchar](64) NULL,
	[ERPLOGICALID] [nvarchar](255) NULL,
	[ERPTAXID] [nvarchar](64) NULL,
	[ERPPAYMENTTERM] [nvarchar](64) NULL,
	[ERPSTATUSDATE] [datetime] NULL,
	[ERPACCOUNTINGID] [nvarchar](22) NULL,
	[ERPPAYMENTMETHOD] [nvarchar](64) NULL,
	[ERPVARIATIONID] [nvarchar](22) NULL,
	[ERPBUYERCONTACTID] [nchar](12) NULL,
	[ERPUNIQUEID] [nvarchar](377) NULL,
	[ERPDEFAULTWAREHOUSEID] [nchar](12) NULL,
	[ERPSHIPLINECOMPLETE] [nchar](1) NULL,
	[ERPSHIPORDERCOMPLETE] [nchar](1) NULL,
	[ERPSICCODE] [nvarchar](64) NULL,
	[ERPSTATUS] [nvarchar](64) NULL,
	[CARRIERID] [nchar](12) NULL,
	[SYNCSTATUS] [nvarchar](64) NULL,
	[LOCALIZED_ACCOUNT_NAME] [nvarchar](255) NULL,
	[PSSC_LAWSON_ID] [nvarchar](255) NULL,
	[PSSC_ESALES_ID] [nvarchar](255) NULL,
	[PSSC_OWNER_ROLE] [nvarchar](1300) NULL,
	[PSSC_SFDC_ACCOUNTID] [nvarchar](1300) NULL,
	[SFDCINTERNALID] [nvarchar](18) NULL,
	[ISDELETED] [nchar](1) NULL,
	[DELETEDDATE] [datetime] NULL,
	[FAMILYID] [nchar](12) NULL,
	[AVENTIONID] [nvarchar](36) NULL,
	[MARKETOID] [int] NULL,
	[DQMATCHPARENTID] [nchar](12) NULL,
	[DQMATCHSTATUS] [nvarchar](64) NULL,
	[MARKETOSTATUS] [nvarchar](12) NULL,
	[MARKETOOPERATION] [nvarchar](12) NULL,
	[MARKETOSYNCMESSAGE] [ntext] NULL,
	[ERPNOTES] [ntext] NULL,
	[ISNORMALIZED] [nchar](1) NULL,
	[MARKETOLASTACTION] [nvarchar](12) NULL,
	[ADDRESSCHANGEDATE] [datetime] NULL,
	[PSSCPARENTACCOUNTID] [nchar](12) NULL
) ON [SECONDARY] TEXTIMAGE_ON [SECONDARY]
GO


